export default{
    getMpmeData: (state) => state.mpmeData,
    getmpme: (state) => state.mpmeAll,
    getRegionOptions: (state) => state.regionOptions,
    getRegionOptions2: (state) => state.regionOptions2,
    getCountryOptions: (state) => state.countryOptions,
    getprefectureOptions : (state) => state.prefectureOptions,
    getSousprefectureOptions : (state) => state.SousprefectureOptions,
    getQuartierOptions : (state) => state.QuartierOptions,
    getsecteurActiviteOptions: (state) => state.secteurActiviteOptions,
    getSousSecteurOptions: (state) => state.sousSecteurOptions,
    getStatutJuridiqueOptions: (state) => state.statutJuridiqueOptions,
    getBourseOptions: (state) => state.bourseOptions,
    loggedInMPME: (state) => state.loggedInMPME,
    getSousDocOptions: (state) => state.sousdocOptions,
    getSousCategoriesData: (state) => state.sousCategoriesData,
    getCategoriesData: (state) => state.categoriesData,
    getTotalEmploisFemme: (state) => state.totalEmploisFemme,
    getTotalMpme: (state) => state.totalMpme,
    getTypeCartesData: (state) => state.typeCartesData,
    getTypeComptabilitesData: (state) => state.typeComptabilitesData,
    getTypeDemandesData: (state) => state.typeDemandesData,

}