export default{
    mpmeData: [],
    getmpme:[],
    regionOptions: [],
    regionOptions2: [],
    countryOptions: [],
    prefectureOptions: [],
    SousprefectureOptions:[],
    QuartierOptions:[],
    secteurActiviteOptions: [],
    sousSecteurOptions: [],
    statutJuridiqueOptions: [],
    bourseOptions: [],
    loggedInMPME: null,
    sousdocOptions:[],
    sousCategoriesData: [],   
    categoriesData: [],
    totalEmploisFemme: 0,
    totalMpme: 0,
    typeCartesData: [], 
    typeComptabilitesData: [], 
    typeDemandesData:[],

}